# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
     
      # Build and test project
      - name: Install ImageMagick
        run: |
          cd ../..
          git clone https://github.com/ImageMagick/ImageMagick.git
          cd ImageMagick
          ./configure --disable-assert --disable-cipher --disable-dependency-tracking --disable-docs --disable-opencl --disable-openmp --disable-shared --enable-silent-rules --without-bzlib --without-djvu --without-dps --without-flif --without-fontconfig --without-fpx --without-freetype --without-gdi32 --without-heic --without-jbig --without-lcms --without-lqr --without-lzma --without-openexr --without-openjp2 --without-pango --without-raqm --without-raw --without-rsvg --without-threads --without-tiff --without-webp --without-wmf --without-x --without-xml --without-zip --without-zlib -without-zstd
          make all
          sudo make install
          
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          make build
      
      - name: Test
        run: |
          cd $GITHUB_WORKSPACE
          make test
